# Generated by Django 4.1.13 on 2023-12-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.CharField(max_length=100, unique=True)),
                ('applicant', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('food_items', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('schedule_url', models.URLField(blank=True, max_length=255)),
            ],
        ),
    ]
